### ISSUE TITLE
Add action.yaml to support local testing

### ISSUE THREAD

**Issue by RDeluxe** [montudor/action-zip#11]
Hi !

I'm trying to local test my workflow using ACT but I'm encountering an issue.

Seems that action-zip lacks an action.yaml file, and [ACT does not like that](https://github.com/nektos/act/issues/246).

It is also a GH [best practice]( https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions) to include one for describing what is included in your actions

I could create a MR with an action file.

**Comment by montudor** [comment]
This should be fixed with #12, please tell me if you have any further issues
